# Copyright 2018 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: channels.knative.dev/v1alpha1
kind: Bus
metadata:
  name: gcppubsub
spec:
  provisioner:
    name: provisioner
    image: github.com/knative/eventing/pkg/buses/gcppubsub/provisioner
    args: [
      "-logtostderr",
      "-stderrthreshold", "INFO",
    ]
    env: &env
    - name: GOOGLE_CLOUD_PROJECT
      value: $PROJECT_ID
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /var/secrets/google/key.json
    volumeMounts:
    - name: google-cloud-key
      mountPath: /var/secrets/google
  dispatcher:
    name: dispatcher
    image: github.com/knative/eventing/pkg/buses/gcppubsub/dispatcher
    args: [
      "-logtostderr",
      "-stderrthreshold", "INFO",
    ]
    env: *env
    volumeMounts:
    - name: google-cloud-key
      mountPath: /var/secrets/google
  volumes:
  - name: google-cloud-key
    secret:
      secretName: gcppubsub-bus-key
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: gcppubsub-bus-ext
spec:
  hosts:
  - "*.googleapis.com"
  - "accounts.google.com"
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
