# Copyright 2020 The Knative Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Downstream

on:
  pull_request:
    branches: [ 'master', 'release-*' ]

jobs:

  downstream-sample-source:
    name: Sample Source
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    env:
      GOPATH: ${{ github.workspace }}

    steps:

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Install Dependencies
      run: |
        go get github.com/google/go-licenses

    - name: Checkout Upstream
      uses: actions/checkout@v2
      with:
        path: ./src/knative.dev/${{ github.event.repository.name }}

    - name: Checkout Downstream
      uses: actions/checkout@v2
      with:
        repository: knative-sandbox/sample-source
        path: ./src/knative.dev/sample-source

    - name: Test Downstream
      uses: knative-sandbox/downstream-test-go@v1.0.1
      with:
        upstream-module: knative.dev/${{ github.event.repository.name }}
        downstream-module: knative.dev/sample-source

  downstream-eventing-kafka-broker:
    name: Eventing Kafka Broker
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    env:
      GOPATH: ${{ github.workspace }}

    steps:

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Install Dependencies
        run: |
          go get github.com/google/go-licenses

      - name: Checkout Upstream
        uses: actions/checkout@v2
        with:
          path: ./src/knative.dev/${{ github.event.repository.name }}

      - name: Checkout Downstream
        uses: actions/checkout@v2
        with:
          repository: knative-sandbox/eventing-kafka-broker
          path: ./src/knative.dev/eventing-kafka-broker

      - name: Test Downstream
        uses: knative-sandbox/downstream-test-go@v1.0.1
        with:
          upstream-module: knative.dev/${{ github.event.repository.name }}
          downstream-module: knative.dev/eventing-kafka-broker

  downstream-eventing-kafka:
    name: Eventing Kafka
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    env:
      GOPATH: ${{ github.workspace }}

    steps:

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Install Dependencies
        run: |
          go get github.com/google/go-licenses

      - name: Checkout Upstream
        uses: actions/checkout@v2
        with:
          path: ./src/knative.dev/${{ github.event.repository.name }}

      - name: Checkout Downstream
        uses: actions/checkout@v2
        with:
          repository: knative-sandbox/eventing-kafka
          path: ./src/knative.dev/eventing-kafka

      - name: Test Downstream
        uses: knative-sandbox/downstream-test-go@v1.0.1
        with:
          upstream-module: knative.dev/${{ github.event.repository.name }}
          downstream-module: knative.dev/eventing-kafka
